# Responder con una redirección temporal para cualquier sitio de
# verificación de portales cautivos.  Esto hace que el sitio principal se
# abra apenas el dispositivo se conecta a la WiFi.
#
# @see https://github.com/mortonfox/captive-portal-test/blob/main/captive_portal.html
# @see https://support.mozilla.org/en-US/kb/captive-portal
server {
  listen 80;

  server_name clients3.google.com www.gstatic.com 172.217.6.238
    captiveportal.kuketz.de e.foundation elementary.io httpstat.us
    captive.apple.com www.apple.com attwifi.apple.com www.msftncsi.com
    detectportal.firefox.com connectivitycheck.android.com
    connectivitycheck.gstatic.com play.googleapis.com www.google.com
    ping.archlinux.org;

  return 307 https://nodo.sutty.nl;
}
