# Esta es básicamente la configuración de sutty.nl menos las opciones de
# TLS.
# @see https://0xacab.org/sutty/ansible-sutty/-/blob/master/templates/sites.conf.j2
server {
  server_name _;

  listen 80 default_server;
  listen 443 ssl http2 default_server;

  add_header Cache-Control no-cache;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
  add_header X-Frame-Options "sameorigin";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options "nosniff";
  add_header Referrer-Policy "strict-origin-when-cross-origin";
  add_header Access-Control-Allow-Origin "*";
  add_header Permissions-Policy "interest-cohort=()";

  ssl_certificate /etc/letsencrypt/live/$ssl_server_name/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/$ssl_server_name/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_early_data on;

  if ($redirect_to_https) {
    return 301 https://$http_host$request_uri;
  }

  root /srv/http/$ssl_server_name;

  error_page 404 =404 @404;

  location @404 {
    try_files /default/404.html @404_site_not_found;
  }

  location @404_site_not_found {
    root /srv/http/sutty.nl/default;
    try_files /404_site_not_found.html =404;
  }

  default_type "text/html";

  location /sandboxed/ {
    add_header X-Frame-Options "";
    try_files $request_uri $uri $uri/ =404;
  }

  location / {
    try_files $request_uri $uri $uri/ =404;
  }
}
